(function(g){var window=this;'use strict';var F3=function(a){a.publish("cardstatechange",a.Hk()&&a.Xo()?1:0)},G3=function(a,b){var c=g.ab(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},eob=function(a){var b=g.Is(a);
a=g.Ls(a);return new g.ws(b.x,b.y,a.width,a.height)},fob=function(a,b,c){var d=void 0===d?{}:d;
var e;return e=g.WB(a,b,function(){g.XB(e);c.apply(a,arguments)},d)},J3=function(a){a=g.fb(a);
delete H3[a];g.id(H3)&&I3&&I3.stop()},hob=function(){I3||(I3=new g.fv(function(){gob()},20));
var a=I3;a.isActive()||a.start()},gob=function(){var a=g.kb();
g.Vc(H3,function(b){iob(b,a)});
g.id(H3)||hob()},K3=function(a,b,c,d){g.yv.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.B=a;this.N=b;this.duration=c;this.G=d;this.coords=[];this.progress=this.K=0;this.D=null},iob=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.K=1E3/(b-a.D);a.D=b;job(a,a.progress);1==a.progress?(a.j=0,J3(a),a.onFinish(),a.Br()):a.isPlaying()&&a.hM()},job=function(a,b){"function"===typeof a.G&&(b=a.G(b));
a.coords=Array(a.B.length);for(var c=0;c<a.B.length;c++)a.coords[c]=(a.N[c]-a.B[c])*b+a.B[c]},kob=function(a,b){g.zb.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.K;this.state=b.j},L3=function(a,b,c,d,e){K3.call(this,b,c,d,e);
this.element=a},lob=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
L3.call(this,a,b,c,d,e)},mob=function(a){return Math.pow(a,3)},nob=function(a){return 3*a*a-2*a*a*a},oob=function(a){g.I.call(this);
this.B=a||window;this.j=[]},M3=function(a){return a.baseUrl||null},N3=function(a,b){return g.Ht(g.Rr(a,b),function(c){return!!c})},pob=function(a,b,c){function d(ka){var ia=ka.hovercardButton;
if(!ia)return null;ia=ia.subscribeButtonRenderer;if(!ia)return null;var sa=f(ia.unsubscribedButtonText),aa=f(ia.subscribedButtonText);if(ia.subscribed){var U=f(ia.subscriberCountWithUnsubscribeText);var Ja=f(ia.subscriberCountText)}else U=f(ia.subscriberCountText),Ja=f(ia.subscriberCountWithSubscribeText);var x=null;if(ka.signinEndpoint){x=G3(ka,"signinEndpoint","webNavigationEndpointData","url");if(!x){var ba,La;x=null==(La=g.V(null==(ba=ia.signInEndpoint)?void 0:ba.commandMetadata,g.y2))?void 0:
La.url}if(!x)return null}return sa&&(aa||x)?{subscribed:ia.subscribed,subscribeText:sa,subscribeCount:U,unsubscribeText:aa,unsubscribeCount:Ja,enabled:ia.enabled,signinUrl:x,classic:ka.useClassicSubscribeButton}:null}
function e(ka){if(ka){var ia=[],sa=ka.videoId;sa&&ia.push("v="+sa);(sa=ka.playlistId)&&ia.push("list="+sa);(ka=ka.startTimeSeconds)&&ia.push("t="+ka);return"/watch?"+ia.join("&")}}
function f(ka){if(!ka)return null;var ia=ka.simpleText;return ia?ia:ka.runs?g.Rr(ka.runs,function(sa){return sa.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,r=null,t=null,v=null,w=!1,A=null,C=null,F=null,H=null,L=null,M=null;if("VIDEO"===h)g.V(l,g.GF)?m=g.V(l,g.GF).url:(M=g.V(l,g.RS),m=e(M)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,r=f(p.text),p="LIVE"===p.style):r=f(b.videoDuration);else if("PLAYLIST"===h)g.V(l,g.GF)?m=g.V(l,g.GF).url:(M=g.V(l,g.RS),m=e(M)),n=!1,q=a,t=f(b.playlistLength);else if("CHANNEL"===
h){if(w=G3(l,"browseEndpoint","browseId"))v=w,m="/channel/"+v;n=!1;q="new";(w=!!b.isSubscribe)?A=d(b):C=f(b.subscribersText)}else"WEBSITE"===h?((F=G3(l,"urlEndpoint","url"))&&(m=F),n=!0,q="new",F=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(H=f(b.productPrice)),b.additionalFeesText&&(L=f(b.additionalFeesText)),(n=G3(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=G3(b,"title","accessibility","accessibilityData","label");var R=b.endpoint?b.endpoint.clickTrackingParams:null,
fa="";if(b.metadata){var na=f(b.metadata);na&&(fa=na)}return{id:"element-"+c,type:h,title:f(b.title),metadata:fa,callToAction:f(b.callToAction),SW:b.image,iconUrl:F,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,BE:p,playlistLength:t,channelId:v,subscribeButton:A,subscribersText:C,isSubscribe:w,targetUrl:m||null,f9:n,sessionData:R?{itct:R}:null,xda:q,YC:a?a:null,isPlaceholder:b.isPlaceholder,
impressionUrls:N3(b.impressionUrls||[],M3),T8:N3(b.hovercardShowUrls||[],M3),clickUrls:N3(l.loggingUrls||[],M3),visualElement:g.LE(b.trackingParams),productPrice:H,additionalFeesText:L,watchEndpoint:M||null}},qob=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:N3(a.impressionUrls||[],M3),elements:N3(a.elements||[],function(d,e){return pob(b,d,e)})};
a.trackingParams&&(c.visualElement=g.LE(a.trackingParams));return c},rob=function(a){g.uV.call(this,a);
this.C=this.endscreen=null;this.j={};this.G={};this.D=this.B=null;this.N=[];this.Y=!0;this.K=0;a=a.U();this.Z=g.IR(a)||g.KR(a);this.events=new g.lK(this);g.N(this,this.events);this.events.T(this.player,g.tJ("creatorendscreen"),this.onCueRangeEnter);this.events.T(this.player,g.uJ("creatorendscreen"),this.onCueRangeExit);this.events.T(this.player,"resize",this.dc);this.events.T(window,"focus",this.Kba);this.load();var b=g.yf("STYLE");(g.lf("HEAD")[0]||document.body).appendChild(b);this.addOnDisposeCallback(function(){g.Ff(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},sob=function(a){return a.player.getVideoData().Hf?"current":a.Z?"new":"current"},O3=function(a){return"creator-endscreen-editor"===a.player.U().playerStyle},tob=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.C&&a.C.abort();c={method:"POST",onFinish:function(e){var f=a.C=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=qob(f,sob(a))));P3(a,f)},
urlParams:{v:c},withCredentials:!0};a.Z&&(c.urlParams.ptype="embedded");var d=b.vy;d&&(c.postParams={ad_tracking:d});if(b=g.aWa(b))if(b=g.fe(b),b=g.$d(b))a.C=g.mB(b,c)},P3=function(a,b,c){c=void 0===c?!0:c;
a.player.rf("creatorendscreen");a.B&&(a.B.dispose(),a.B=null,a.D.dispose(),a.D=null);for(var d=g.u(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.G={};0<a.N.length&&(a.N.forEach(function(l){l.dispose()}),a.N.length=0);
a.K=0;if((a.endscreen=b)&&b.elements){c&&uob(a);c=[];d=new g.sJ(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.U().B||(a.B=new g.W({I:"div",S:"ytp-ce-shadow"}),g.WT(a.player,a.B.element,4),a.D=new g.UF(a.B,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=vob(a,e);if(f){a.j[e.id]=f;a.G[e.id]=e;g.WT(a.player,f.element,4);var h=new g.sJ(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);wob(a,f,e)}else g.RE(new g.mC("buildEndscreenElement null",
e))}a.player.kf(c);a.dc()}},uob=function(a){var b=g.ME(),c=g.NE();
c&&b&&a.endscreen.visualElement&&g.TA(g.ZE)(void 0,c,b,a.endscreen.visualElement)},vob=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={I:"div",Ka:["ytp-ce-element","ytp-ce-video"],X:{tabindex:"0","aria-label":b.YC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",X:Q3(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",X:{href:R3(a,b.targetUrl),tabindex:"-1"},V:[{I:"div",Ka:["ytp-ce-video-title","ytp-webkit-ellipsis"],X:{dir:g.Cv(b.title||"")},xa:b.title},{I:"div",S:b.BE?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
xa:b.videoDuration||void 0}]}]};c=new g.W(a);break;case "PLAYLIST":a={I:"div",Ka:["ytp-ce-element","ytp-ce-playlist"],X:{tabindex:"0","aria-label":b.YC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",X:Q3(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",X:{href:R3(a,b.targetUrl),tabindex:"-1"},V:[{I:"div",Ka:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],X:{dir:g.Cv(b.title||"")},xa:b.title},{I:"div",S:"ytp-ce-playlist-count",
V:[{I:"div",S:"ytp-ce-playlist-icon"},{I:"div",S:"ytp-ce-playlist-count-text",xa:b.playlistLength||void 0}]}]}]};c=new g.W(a);break;case "CHANNEL":c={I:"div",Ka:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],X:{tabindex:"0","aria-label":b.YC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"a",Ka:["ytp-ce-channel-title","ytp-ce-link"],X:{href:R3(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Cv(b.title||"")},xa:b.title},b.subscribeButton?{I:"div",S:"ytp-ce-subscribe-container",V:[{I:"div",S:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{I:"div",S:"ytp-ce-channel-subscribers-text",xa:b.subscribersText}:"",b.metadata?{I:"div",Ka:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],xa:b.metadata}:""]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",X:Q3(b)}]};c=new g.W(c);var d=g.mf(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.tv(d,"ytp-ce-subscribe-button");if(a.player.U().B){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.dW(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,
b.channelId,!!b.subscribeButton.subscribed,e,f,a.player,!1);d.appendChild(e.element);a.N.push(e)}break;case "WEBSITE":a={I:"div",Ka:["ytp-ce-element","ytp-ce-website"],X:{tabindex:"0","aria-label":b.YC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",
S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-website-title",X:{dir:g.Cv(b.title||"")},xa:b.title},{I:"div",S:"ytp-ce-website-metadata",xa:b.metadata},{I:"a",Ka:["ytp-ce-website-goto","ytp-ce-link"],X:{href:R3(a,b.targetUrl),target:"_blank",tabindex:"-1"},xa:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",X:Q3(b)},{I:"div",S:"ytp-ce-expanding-icon",X:xob(b.iconUrl)}]};c=new g.W(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={I:"div",S:"ytp-ce-merchandise-price-container",
V:[{I:"div",S:"ytp-ce-merchandise-price",xa:b.productPrice}]},b.additionalFeesText&&c.V.push({I:"div",S:"ytp-ce-merchandise-additional-fees",xa:b.additionalFeesText})),a={I:"div",Ka:["ytp-ce-element","ytp-ce-merchandise"],X:{tabindex:"0","aria-label":b.YC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-merchandise-title",X:{dir:g.Cv(b.title||"")},xa:b.title},c,{I:"div",S:"ytp-ce-merchandise-metadata",xa:b.metadata},{I:"a",Ka:["ytp-ce-merchandise-goto","ytp-ce-link"],X:{href:R3(a,b.targetUrl),target:"_blank",tabindex:"-1"},xa:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",X:Q3(b)},{I:"div",S:"ytp-ce-merchandise-invideo-cta-container",V:[{I:"div",S:"ytp-ce-merchandise-invideo-cta",
xa:b.callToAction||void 0}]}]},c=new g.W(a)}b.isPlaceholder&&g.tv(c.element,"ytp-ce-placeholder");return c},Q3=function(a){if(a.SW)var b=a.SW.thumbnails;
return xob(b?b[b.length-1].url:null)},xob=function(a){return a?{style:"background-image: url("+a+")"}:{}},wob=function(a,b,c){function d(m){m&&(b.listen("blur",function(){"none"!=m.style.display&&a.Y&&m.focus()}),b.T(m,"focus",f),b.T(m,"blur",h))}
function e(m){a.K+=m;0<a.K?(g.tv(b.element,"ytp-ce-force-expand"),S3(a,c.id,!0)):(g.vv(b.element,"ytp-ce-force-expand"),g.vv(b.element,"ytp-ce-element-hover"),S3(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.listen("mouseenter",function(){yob(a,b,c)});
b.listen("mouseleave",function(){zob(a,b,c)});
a.player.U().B||b.listen("click",function(){g.tv(b.element,"ytp-ce-element-hover")});
b.listen("click",function(m){Aob(a,c,m)});
b.listen("keypress",function(m){Aob(a,c,m)});
b.listen("focus",function(){yob(a,b,c)});
b.listen("blur",function(){zob(a,b,c)});
b.listen("touchstart",function(){yob(a,b,c)});
var l=g.tf("ytp-ce-expanding-overlay-hider",b.element);l&&b.T(l,"touchstart",function(m){m.stopPropagation();g.vv(b.element,"ytp-ce-element-hover");g.vv(b.element,"ytp-ce-force-expand")});
b.listen("keydown",function(m){a.Y=9===m.keyCode&&!m.shiftKey});
d(g.tf("ytp-sb-subscribe",b.element));d(g.tf("ytp-sb-unsubscribe",b.element));b.listen("focus",f);b.listen("blur",h)},Aob=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.rv(d,"ytp-ce-element");){g.rv(d,"subscribe-label")&&Bob(a,b);
if(g.rv(d,"ytp-ce-channel-subscribe"))return;d=g.Mf(d)}if(!d||g.rv(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])zob(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.xda)Bob(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.fe(R3(a,b.targetUrl)),c=g.$d(c),g.AG(c,void 0,b.sessionData);else{var e=g.TR(a.player.U())||a.player.getVideoData().Hf,f=function(){var h=R3(a,b.targetUrl),l=b.sessionData,m=b.watchEndpoint,n=g.YA(h);e&&n&&
(n.v||n.list)?a.player.Jo(n.v,l,n.list,!1,void 0,m||void 0):g.eya(h,l)};
Bob(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},R3=function(a,b){a=a.player.U();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.aS(a)+b}else return"";return b},yob=function(a,b,c){g.rv(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.tv(b.element,"ytp-ce-element-hover"):a.player.U().B?(new g.fv(function(){g.tv(b.element,"ytp-ce-element-hover")},200)).start():g.tv(b.element,"ytp-ce-element-hover"),T3(a,c.T8),S3(a,c.id,!0))},zob=function(a,b,c){g.vv(b.element,"ytp-ce-element-hover");
g.vv(b.element,"ytp-ce-force-expand");S3(a,c.id,!1)},S3=function(a,b,c){a.B&&(c?a.D.show():a.D.hide());
for(var d=g.u(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.xv(a.j[e].element,"ytp-ce-element-shadow-show",c)},T3=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||O3(a))c&&c();else{b=Cob(a,b);var e=0,f=!1,h=new g.fv(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.GD(b[a],d)}},Bob=function(a,b,c){T3(a,b.clickUrls,c);
(a=g.NE())&&b.f9&&g.fF(a,b.visualElement)},Cob=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(Dob(b[d],c));return a},Dob=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},Eob=function(a){return"string"===typeof a?a:""},U3=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},Fob=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},V3=function(a){return a.value?a.value:null},W3=function(a){if(!a)return null;
var b=g.fe(Eob(a.value));b=g.$d(b);if(!b)return null;var c=U3(a.target,Gob,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new Fob(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},Hob=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},Kob=function(a){if(!a)return null;
var b=U3(a.type,Iob),c=U3(a.trigger,Job);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=W3(a?a:null);return b?new Hob(b,c,a):null},Lob=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},Mob=function(a,b){return g.Db(a.action,b)},Nob=function(a,b){this.context=a;
this.j=b},Oob=function(a){return a.customMessage?X3("div","iv-card-message",a.customMessage):""},Y3=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{I:"div",S:"iv-card-image",X:{style:a},V:c}},Pob=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.u(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(X3("li","",c.value));return{I:"ul",S:"iv-card-meta-info",V:b}},X3=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Cv(c);return{I:a,X:b,xa:c}},Qob=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.jD&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.jD+");");c.dir=g.Cv(a.customMessage);var d=[{I:"span",xa:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({I:"span",S:"iv-card-link-icon"}));return{I:"div",Ka:b,X:c,V:d}},Z3=function(a,b,c,d){if(d){b=g.u(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.aj.click,5)}},Rob=function(a,b){this.merchant=a;
this.price=b},Sob=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},Tob=function(a,b){return b?b:Sob(a)?"current":"new"},$3=function(a,b){g.I.call(this);
var c=this;this.element=a;this.context=b;this.rb=!1;this.Wa=new Map;this.bb=new Map;this.context.J.addEventListener(g.tJ("annotations_module"),function(d){(d=c.Wa.get(d))&&d.apply(c)});
this.context.J.addEventListener(g.uJ("annotations_module"),function(d){(d=c.bb.get(d))&&d.apply(c)})},a4=function(a,b,c,d,e,f,h){a.context.j.listen(b,"click",function(l){a.iM(c,d,e,f||[],h||0,l)});
a.context.j.listen(b,"touchstart",function(){a.rb=!1});
a.context.j.listen(b,"touchmove",function(){a.rb=!0})},Uob=function(a){var b;
return(null==(b=g.V(a,g.GF))?0:b.url)?g.V(a,g.GF).url:(a=g.V(a,g.RS))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},b4=function(a,b,c){return{oY:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
X0:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
zL:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},Vob=function(a,b,c){$3.call(this,b,c);
var d=this;this.J=a;this.eventId=null;this.Gb=this.Na=this.Jb=this.C=this.isInitialized=!1;this.cards=[];this.zb=this.Z=this.La=this.G=this.Va=this.j=null;this.qa=[];this.ra=this.N=this.Ef=this.Ea=null;this.K=0;this.Ga=new g.fv(function(){},c.W.Cl?4E3:3E3);
g.N(this,this.Ga);this.eb=new g.fv(function(){});
g.N(this,this.eb);this.Ca=new Nob(c,function(e,f,h,l,m,n){a4(d,e,f,h,l,m,n)});
this.Y=new g.W({I:"div",S:"iv-drawer",X:{id:"iv-drawer"},V:[{I:"div",S:"iv-drawer-header",X:{"aria-role":"heading"},V:[{I:"span",S:"iv-drawer-header-text"},{I:"button",Ka:["iv-drawer-close-button","ytp-button"],X:{"aria-label":"Hide cards",tabindex:"0"}}]},{I:"div",S:"iv-drawer-content"}]});g.N(this,this.Y);this.D=this.Y.element;this.Za=new g.UF(this.Y,330);g.N(this,this.Za);this.Hb=g.tf("iv-drawer-header-text",this.D);this.B=g.tf("iv-drawer-content",this.D);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.Jb&&c4(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Jb=d.C)&&d4(d)});
this.Ra=new g.lK(this);g.N(this,this.Ra);this.J.addEventListener("videodatachange",this.vt.bind(this))},Wob=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){c4(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){d4(a)});
var c=b.headerText;g.Of(a.Hb,c);a.Z&&a.Z.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Ea=g.LE(b.trackingParams);a.N=g.LE(b.closeTrackingParams);a.Ef=g.LE(b.iconTrackingParams)},Xob=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.K,d=a.J.U().experiments.gb("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.tF(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,aj:{},fp:null,Fj:e.trackingParams?g.LE(e.trackingParams):null,Ef:f&&f.trackingParams?g.LE(f.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
jD:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};e4(a,b)}else{var h;if(null==(h=b.content)?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=null==(e=b.content)?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.tF(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,
sessionData:f4(a,c,b,f),sponsored:!1,aj:b4(f,e,f.command),fp:f.trackingParams?g.LE(f.trackingParams):null,Fj:e.trackingParams?g.LE(e.trackingParams):null,Ef:l&&l.trackingParams?g.LE(l.trackingParams):null,imageUrl:g4(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.tF(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,jD:null,title:f.title?g.tF(f.title):"",customMessage:f.callToAction?g.tF(f.callToAction):"",url:g.V(f.command,g.GF).url?W3({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.V(f.command,g.GF).url}):null,onClickCommand:null};e4(a,b)}else{var m;if(null==(m=b.content)?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(f=b.content)?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"collaborator",teaserText:g.tF(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:f4(a,c,b,e),sponsored:!1,aj:b4(e,f,e.endpoint),fp:e.trackingParams?g.LE(e.trackingParams):null,Fj:f.trackingParams?g.LE(f.trackingParams):null,Ef:l&&l.trackingParams?g.LE(l.trackingParams):null,channelId:g.V(e.endpoint,g.fT).browseId,customMessage:e.customText?g.tF(e.customText):null,profileImageUrl:g4(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.tF(e.channelName):"",metaInfo:[e.subscriberCountText?g.tF(e.subscriberCountText):""],url:W3({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.V(e.endpoint,g.fT).canonicalBaseUrl?g.V(e.endpoint,g.fT).canonicalBaseUrl:"/channel/"+g.V(e.endpoint,g.fT).browseId}),onClickCommand:null};e4(a,b)}else{var n;if(null==(n=b.content)?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(l=b.content)?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"playlist",teaserText:g.tF(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:f4(a,c,b,e),sponsored:!1,aj:b4(e,f,e.action),fp:e.trackingParams?g.LE(e.trackingParams):null,Fj:f.trackingParams?g.LE(f.trackingParams):null,Ef:l&&l.trackingParams?g.LE(l.trackingParams):null,OG:g4(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.tF(e.customMessage):null,playlistVideoCount:g.tF(e.playlistVideoCount),title:e.playlistTitle?g.tF(e.playlistTitle):"",metaInfo:[e.channelName?g.tF(e.channelName):
"",e.videoCountText?g.tF(e.videoCountText):""],url:W3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:Uob(e.action)}),onClickCommand:null};e4(a,b)}else{var p;if(null==(p=b.content)?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=null==(q=b.content)?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"video",teaserText:g.tF(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:f4(a,c,b,e),sponsored:!1,aj:b4(e,f,e.action),fp:e.trackingParams?g.LE(e.trackingParams):null,Fj:f.trackingParams?g.LE(f.trackingParams):null,Ef:l&&l.trackingParams?g.LE(l.trackingParams):null,OG:g4(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.tF(e.lengthString):null,customMessage:e.customMessage?g.tF(e.customMessage):null,title:e.videoTitle?g.tF(e.videoTitle):"",metaInfo:[e.channelName?g.tF(e.channelName):
"",e.viewCountText?g.tF(e.viewCountText):""],isLiveNow:!!e.badge,url:W3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:Uob(e.action)}),onClickCommand:null};e4(a,b)}}}}}a.K++},g4=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},f4=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},Zob=function(a,b){if(b=Yob(a,b))b===a.j&&(a.j=null),a.J.removeCueRange(b.zf.id),g.Ff(b.BN),g.Hb(a.cards,b),a.RH(),h4(a)},c4=function(a,b,c){if(!a.C){a.Za.show();
a.Va=new g.fv(function(){g.tv(a.context.J.getRootNode(),g.JY.IV_DRAWER_OPEN)},0);
a.Va.start();a.Ra.T(a.B,"mousewheel",function(h){a.Ga.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.B.scrollTop+=h});
a.C=!0;var d=g.NE();d&&a.Ea&&a.N&&g.dF(d,[a.Ea,a.N]);b={TRIGGER_TYPE:b};for(var e=g.u(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.hZ||(f.hZ=!0,$ob(a.context.logger,f.zf.aj.oY,b)),d&&g.dF(d,[f.zf.fp]);F3(a.J);c&&(a.G=new g.fv(function(){a.La=a.Z;a.zb.focus()},330),a.G.start())}},d4=function(a){a.C&&(a.Za.hide(),g.bC(a.Ra),g.vv(a.context.J.getRootNode(),g.JY.IV_DRAWER_OPEN),a.C=!1,F3(a.J),a.G&&a.G.stop(),a.G=new g.fv(function(){a.La&&(a.La.focus(),a.La=null)},330),a.G.start())},bpb=function(a){g.uv(a.Ib(),
[g.JY.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.WT(a.J,a.D,5);apb(a);a.Z=g.tf("ytp-cards-button",a.J.getRootNode());a.zb=g.tf("iv-drawer-close-button",a.D);a.isInitialized=!0},apb=function(a){var b=g.tf("iv-drawer-close-button",a.D);
a.context.j.listen(b,"click",a.B6,a);a.context.j.listen(a.B,"touchend",function(){a.Ga.start()});
a.context.j.listen(a.B,"scroll",a.Y6,a);a.context.B.subscribe("onHideControls",function(){a.Na=!0});
a.context.B.subscribe("onShowControls",function(){a.Na=!1});
a.context.B.subscribe("onVideoAreaChange",function(){a.Na=g.rv(a.J.getRootNode(),"ytp-autohide")});
a.qa.push(g.UD("iv-button-shown",a.x9,a));a.qa.push(g.UD("iv-button-hidden",a.w9,a));cpb(a)},cpb=function(a){a.qa.push(g.UD("iv-teaser-shown",a.E3,a));
a.qa.push(g.UD("iv-teaser-hidden",a.y9,a));a.qa.push(g.UD("iv-teaser-clicked",a.D3,a));a.Gb=!0},dpb=function(a,b){var c;
return b.onClickCommand&&"engagement-panel-error-corrections"===(null==(c=g.V(b.onClickCommand,g.Gkb))?void 0:c.targetId)?(a.ra=b,!0):!1},epb=function(a,b){a.ra=b;
var c=a.J.getVideoData();if(!c)return!1;c=g.yUa(c);if(null==c?0:c.markersMap)for(var d,e=0;(null==(d=c)?void 0:d.markersMap.length)>e;e++){var f=void 0,h=null==(f=c)?void 0:f.markersMap[e];if("ERROR_CORRECTION_MARKERS"===h.key&&(f=void 0,(h=null==(f=h.value)?void 0:f.markers)&&0<h.length))return d=void 0,b.startMs=(null==(d=g.V(h[0],g.Y1a))?void 0:d.timeRangeStartMillis)||0,a.ra=null,!0}return!1},e4=function(a,b){if(!dpb(a,b)||epb(a,b)){var c=fpb(a,b);
if(c){var d={zf:b,BN:c.element,hZ:!1};if(b.onClickCommand)a.J.L("web_infocards_teaser_show_logging_fix")&&(a.Gb||cpb(a),Zob(a,b.id),c=a.findLastIndex(d),g.Ob(a.cards,c,0,d));else{a.isInitialized||bpb(a);Zob(a,b.id);var e=a.findLastIndex(d);g.Ob(a.cards,e,0,d);c.Ja(a.B,e);a.RH()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.C||(a.j=d,h4(a),gpb(a,d),c4(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.J.getCurrentTime(),5E3>c&&c>b.startMs&&hpb(a,d),a.addCueRange(b.startMs,
b.startMs+1,b.id,function(){hpb(a,d)}),h4(a))}}},fpb=function(a,b){switch(b.type){case "simple":a=a.Ca;
var c=b.displayDomain?{I:"div",S:"iv-card-image-text",xa:b.displayDomain}:void 0;var d=Qob(b);c={I:"div",Ka:["iv-card"],V:[{I:"a",S:"iv-click-target",X:{href:b.url?V3(b.url)||"":""},V:[Y3(b.imageUrl,c),{I:"div",S:"iv-card-content",V:[X3("h2",void 0,b.title),d]}]}]};c=new g.W(c);Z3(a,g.sf("iv-click-target",c.element),b,b.url);b=c;break;case "collaborator":a=a.Ca;c={I:"div",Ka:["iv-card","iv-card-channel"],V:[{I:"a",Ka:["iv-click-target"],X:{href:V3(b.url)||"","data-ytid":b.channelId},V:[Y3(b.profileImageUrl),
{I:"div",S:"iv-card-content",V:[Oob(b),{I:"h2",S:"iv-card-primary-link",xa:b.title},Pob(b)]}]}]};c=new g.W(c);Z3(a,g.sf("iv-click-target",c.element),b,b.url);b=c;break;case "playlist":a=a.Ca;c={I:"div",Ka:["iv-card","iv-card-playlist"],V:[{I:"a",S:"iv-click-target",X:{href:V3(b.url)||""},V:[Y3(b.OG,{I:"div",S:"iv-card-image-overlay",V:[{I:"span",S:"iv-card-playlist-video-count",xa:b.playlistVideoCount}]}),{I:"div",S:"iv-card-content",V:[Oob(b),X3("h2","iv-card-primary-link",b.title),Pob(b)]}]}]};
c=new g.W(c);Z3(a,g.sf("iv-click-target",c.element),b,b.url);b=c;break;case "productListing":a=a.Ca;var e=0!=b.offers.length;c=["iv-card"];d="";var f=Qob(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({I:"div",S:"iv-card-offer-price",xa:f.price}),f.merchant&&e.push({I:"div",S:"iv-card-offer-merchant",xa:f.merchant}),f={I:"div",V:e});e=b.url?V3(b.url)||"":"";c={I:"div",Ka:c,X:{tabindex:"0"},V:[{I:"a",Ka:["iv-card-image","iv-click-target"],X:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{I:"div",S:"iv-card-content",V:[b.sponsored?{I:"div",S:"iv-card-sponsored",V:["Sponsored",{I:"div",S:"iv-ad-info-container",V:[{I:"div",S:"iv-ad-info",xa:"{{adInfo}}"},{I:"div",S:"iv-ad-info-icon-container",V:[{I:"div",S:"iv-ad-info-icon"},{I:"div",S:"iv-ad-info-callout"}]}]}]}:"",{I:"a",S:"iv-click-target",X:{href:e},V:[X3("h2",d,b.title),f]}]}]};c=new g.W(c);d=g.yf("span");g.Of(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
c.Kd(d,"adInfo");Z3(a,g.sf("iv-click-target",c.element),b,b.url);b=c;break;case "video":a=a.Ca;d=b.videoDuration?{I:"span",S:"iv-card-video-duration",xa:b.videoDuration}:void 0;f=b.isLiveNow?{I:"span",Ka:["yt-badge","yt-badge-live"],xa:"LIVE NOW"}:null;e={I:"div",Ka:["iv-card","iv-card-video"],V:[{I:"a",S:"iv-click-target",X:{href:(null==(c=b.url)?void 0:V3(c))||""},V:[Y3(b.OG,d),{I:"div",S:"iv-card-content",V:[Oob(b),X3("h2","iv-card-primary-link",b.title),Pob(b),f]}]}]};c=new g.W(e);Z3(a,g.sf("iv-click-target",
c.element),b,b.url);b=c;break;default:return null}return b},ipb=function(a){if(a.j)return"productListing"===a.j.zf.type;
if(a.J.L("enable_wn_infocards")){var b;return!(null==(b=a.cards)||!b.length)&&g.Sr(a.cards,function(c){return"productListing"===c.zf.type})}return g.Sr(a.cards,function(c){return"productListing"===c.zf.type})},h4=function(a){g.xv(a.J.getRootNode(),"ytp-cards-shopping-active",ipb(a))},hpb=function(a,b){if(!g.rv(a.J.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.NE(),d=a.j?a.j.zf.Ef:a.Ef;
c&&d&&g.eF(c,[d]);a.j=b;h4(a)}(c=a.isInitialized&&"none"==a.Ib().style.display)||(c=a.context.J.getPlayerState(),d=0===c&&0===a.context.J.getCurrentTime(),c=!(1===c||3===c||d));c||b.zf.teaserDurationMs&&a.J.zB(!0,{teaserText:b.zf.teaserText,durationMs:b.zf.teaserDurationMs,onClickCommand:b.zf.onClickCommand});a.eb.isActive()||((!a.C||!a.Ga.isActive()&&a.Na)&&gpb(a,b),a.eb.start(910+b.zf.teaserDurationMs))}},gpb=function(a,b){a.Y.Eb?(b=new K3([0,
a.B.scrollTop],[0,b.BN.offsetTop],600,nob),a.context.C.listen(b,"animate",function(c){a.B.scrollTop=c.y}),a.context.C.listen(b,"finish",function(c){a.B.scrollTop=c.y}),b.play()):(g.pF(a.Y,!0),a.B.scrollTop=b.BN.offsetTop,g.pF(a.Y,!1))},i4=function(a){return a.j&&a.j.zf?a.j.zf:a.cards[0]&&a.cards[0].zf?a.cards[0].zf:null},Yob=function(a,b){return g.Db(a.cards,function(c){return c.zf.id===b})},j4=function(a,b,c){$3.call(this,a,b);
this.annotation=c;this.isActive=!1},jpb=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},k4=function(a,b,c){j4.call(this,a,b,c);
this.B=null;this.N=!1;this.C=null;this.D=!1;this.j=this.K=this.G=null},kpb=function(a,b){var c=void 0===c?0:c;
var d=eob(b).width;g.Gs(b,d);c=new lob(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,mob);g.N(a,c);a.context.C.listen(c,"begin",function(){g.Ms(b,!0)});
c.play()},npb=function(a,b){if(b.channel_name){var c=a.createElement({I:"div",
Ka:["iv-branding-context-name"],xa:b.channel_name}),d=a.createElement({I:"div",Ka:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.dW(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,a.context.J,!1),a.j.Ja(d));var f=a.createElement({I:"div",Ka:["iv-branding-context-subscribe-caret"]}),h=a.createElement({I:"div",Ka:["branding-context-container-inner"]});h.appendChild(f);
h.appendChild(c);h.appendChild(d);g.Ms(h,!1);var l=a.createElement({I:"div",Ka:["branding-context-container-outer"]});l.appendChild(h);g.zs(l,"right",b.image_width+"px");g.Af(a.Ib(),l);a.C=new g.fv(function(){lpb(a,h,l)},500);
g.N(a,a.C);a.context.j.listen(a.Ib(),"mouseover",function(){mpb(a,h,l,f,b.image_height)});
a.context.j.listen(a.Ib(),"mouseout",function(){a.C.start()})}},mpb=function(a,b,c,d,e){a.C.stop();
if(!a.D){var f=g.Ls(b);a.j||(b.style.width=g.Fs(f.width,!0),c.style.width=g.Fs(f.width,!0));g.zs(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.zs(d,"right","1px");a.D=!0;g.Ms(b,!0);a.G=new g.fv(function(){g.tv(this.Ib(),"iv-branding-active")},0,a);
a.G.start()}},lpb=function(a,b,c){g.vv(a.Ib(),"iv-branding-active");
a.K=new g.fv(function(){g.Ms(b,!1);a.j||(c.style.width=g.Fs(0,!0))},250);
a.K.start();a.D=!1},opb=function(a,b,c,d,e,f,h){this.j=a;
this.C=b;this.W=c;this.videoData=d;this.logger=e;this.J=f;this.B=h},ppb=function(a,b,c){j4.call(this,a,b,c);
var d=this;this.Z=this.isCollapsed=this.Y=!1;this.K=5E3;this.B=this.C=this.j=this.D=null;this.N=this.createElement({I:"div",Ka:["iv-promo-contents"]});this.G=new g.fv(function(){d.j.setAttribute("aria-hidden","true");g.Ms(d.C,!1);g.Ms(d.B,!0)},700,this);
g.N(this,this.G)},spb=function(a,b,c){c.stopPropagation();
qpb(a);rpb(a,b);a.j.focus()},tpb=function(a){a.isCollapsed||a.Z||a.D||(g.tv(a.Ib(),"iv-promo-collapsed"),a.isCollapsed=!0,a.G.start())},qpb=function(a){a.G.stop();
a.isCollapsed&&(g.wv(a.Ib(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.Ms(a.B,!1),g.Ms(a.C,!0))},rpb=function(a,b){a.D||(a.D=g.Bg(function(){upb(this);
tpb(this)},b,a))},upb=function(a){a.D&&(g.Ta.clearTimeout(a.D),a.D=null)},vpb=function(a){this.J=a},$ob=function(a,b,c){b&&(c?l4(a,b.map(function(d){return g.Wu(d,c)})):l4(a,b))},l4=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.u(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.GD(m,f);d&&(e++,0!==d&&a.J.sendVideoStatsEngageEvent(d,f))},wpb=function(a){g.uV.call(this,a);
var b=this;this.qa=this.Z=!1;this.loadNumber=0;this.K={};this.logger=new vpb(this.player);this.D=new g.lK(this);this.G=this.N=null;this.events=new g.lK(this);this.Rg=this.Y=this.j=null;this.ra=[];g.N(this,this.D);this.D.T(this.player,"onVideoAreaChange",function(){b.publish("onVideoAreaChange")});
this.D.T(this.player,"onHideControls",function(){b.publish("onHideControls")});
this.D.T(this.player,"onShowControls",function(){b.publish("onShowControls")});
this.D.T(this.player,"resize",function(d){b.publish("resize",d)});
this.D.T(this.player,"presentingplayerstatechange",function(d){b.publish("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.F3,this);this.subscribe("resize",this.pK,this);this.player.U().Na.subscribe("vast_info_card_add",this.m_,this);g.N(this,this.events);this.Ca=this.createElement({I:"div",S:"video-custom-annotations"});this.B=new g.W({I:"div",Ka:["ytp-player-content","ytp-iv-player-content"]});g.N(this,this.B);g.WT(this.player,this.B.element,4);this.B.hide();this.C=new g.W({I:"div",Ka:["ytp-iv-video-content"]});g.N(this,this.C);a=this.createElement({I:"div",S:"video-annotations"});
a.appendChild(this.Ca);this.C.element.appendChild(a);this.vu()&&this.load();var c=this.createElement({I:"style"});(g.lf("HEAD")[0]||document.body).appendChild(c);this.addOnDisposeCallback(function(){g.Ff(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},xpb=function(a){a=a.createElement({I:"div",
Ka:["annotation","annotation-type-custom"]});g.Ms(a,!1);return a},ypb=function(a,b){b=!b.isCued()&&!g.$F(b,1024);
g.pF(a.B,b);g.pF(a.C,b)},zpb=function(a,b,c){a.Z=!0;
a.G=g.mB(b,c)},Apb=function(a,b){for(var c={},d=g.u(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.bb(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(Apb(a,e))}return c},Epb=function(a){var b=a.player.getVideoData();
if(b.Va){var c=a.player.U().Na.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=a.loadNumber;f=b.videoId;a.loaded&&a.loadNumber===e&&a.player.getVideoData().videoId===f&&(h=g.fB(h)&&h.responseXML?h.responseXML:null)&&Bpb(a,h)}};
g.uC()&&(d.onFinish=Cpb(a,d.onFinish));d.postParams={ic_only:"1"};Dpb(d,c);a.Z=!0;g.mB(b.Va,d)}}},Dpb=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.WH&&(a.postParams.ic_coll=b.WH);b.CN&&(a.postParams.ic_xml=b.CN);b.EL&&(a.postParams.ic_track=b.EL)},Fpb=function(a){var b=new g.W({I:"div"});
g.Ms(b.element,!1);var c=new Vob(a.player,b.element,m4(a));g.N(c,b);b.Ja(a.B.element);c.xG();return c},Hpb=function(a,b){var c,d;
if(b=null==(c=b.getWatchNextResponse())?void 0:null==(d=c.cards)?void 0:d.cardCollectionRenderer)a.qa=!0,Gpb(a,b),b.headerText&&a.Rg&&(c=g.tF(b.headerText),a.Rg.setAttribute("title",c))},m4=function(a){if(!a.Y){var b=new oob(a);
g.N(a,b);var c=new g.Kp(a);g.N(a,c);a.Y=new opb(b,c,a.player.U(),a.player.getVideoData(),a.logger,a.player,a.pj)}return a.Y},Bpb=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.NE();if(e){var f=g.ME();f&&g.TA(g.Ewa)(void 0,e,f,[g.LE(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=Apb(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=U3(f.type,Ipb),p=U3(f.style,Jpb),q=Eob(f.data),r=0!==q.length?JSON.parse(q):{};var t=f.action;f=Kob;if(null==t)var v=null;else if(g.ab(t)){l=[];for(var w=g.u(t),A=w.next();!A.done;A=w.next()){var C=f(A.value);
C&&l.push(C)}v=l}else{var F=f(t);v=F?[F]:[]}e=m&&n?new Lob(m,n,p,v,r):null}else e=null}catch(na){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var H=xpb(f),L=null;switch(l.type){case "branding":if(f.player.U().Sd)break;f.B.element.appendChild(H);L=new k4(H,m4(f),l);break;case "promotion":g.WT(f.player,H,4),L=new ppb(H,m4(f),l)}L&&L.xG();if(f=L)g.N(a,f),a.K[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.j||(a.j=Fpb(a),g.N(a,a.j));if("card"===e.type){H=a.j;var M=(c=e)&&c.data&&
c.data.card_type;e=c.data;if(M)switch(f=e.tracking||{},f={oY:f.impression,click:f.click,close:f.close,X0:f.teaser_impression,zL:f.teaser_click},l=e.tracking_params||{},L=null,M){case "collaborator":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,aj:f,fp:l.card?g.LE(l.card):null,Fj:l.teaser?g.LE(l.teaser):null,Ef:l.icon?g.LE(l.icon):
null,channelId:e.channel_id,customMessage:e.custom_message?e.custom_message:null,profileImageUrl:e.image_url,title:e.title,metaInfo:e.meta_info,url:W3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};e4(H,c);break;case "playlist":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,aj:f,
fp:l.card?g.LE(l.card):null,Fj:l.teaser?g.LE(l.teaser):null,Ef:l.icon?g.LE(l.icon):null,OG:e.image_url,playlistVideoCount:e.playlist_video_count,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,url:W3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};e4(H,c);break;case "productListing":e.signin_url&&(L=W3({target:"current",value:e.signin_url}));M=[];for(var R=e.offers||[],fa=0;fa<R.length;fa++)M.push(new Rob(g.Ye(R[fa].merchant),
g.Ye(R[fa].price)));c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,aj:f,fp:l.card?g.LE(l.card):null,Fj:l.teaser?g.LE(l.teaser):null,Ef:l.icon?g.LE(l.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,jD:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?
e.custom_message:null,url:W3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),tqb:L,sqb:e.signin_title?e.signin_title:void 0,qqb:e.signin_message?e.signin_message:void 0,offers:M,onClickCommand:null};e4(H,c);break;case "simple":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,aj:f,fp:l.card?g.LE(l.card):
null,Fj:l.teaser?g.LE(l.teaser):null,Ef:l.icon?g.LE(l.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,jD:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?e.custom_message:null,url:W3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};e4(H,c);break;case "video":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,
startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,aj:f,fp:l.card?g.LE(l.card):null,Fj:l.teaser?g.LE(l.teaser):null,Ef:l.icon?g.LE(l.icon):null,OG:e.image_url,videoDuration:e.video_duration||null,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,isLiveNow:!!e.is_live_now,url:W3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null},e4(H,c)}}else Wob(a.j,e);c=!0}}c&&
(F3(a.player),a.pK())},Gpb=function(a,b){var c=!1;
a.j||(a.j=Fpb(a),g.N(a,a.j));for(var d=g.u(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(Xob(a.j,e.cardRenderer),c=!0);if(c){var f;null!=(f=a.player.getVideoData())&&g.mT(f)||(c=a.j,d=b.headerText?g.tF(b.headerText):"",g.Of(c.Hb,d),c.Z&&c.Z.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Ea=b.trackingParams?g.LE(b.trackingParams):null,c.N=b.closeButton.infoCardIconRenderer.trackingParams?g.LE(b.closeButton.infoCardIconRenderer.trackingParams):
null,c.Ef=b.icon.infoCardIconRenderer.trackingParams?g.LE(b.icon.infoCardIconRenderer.trackingParams):null,a.pK());F3(a.player)}},Kpb=function(a,b,c,d,e){if(!a.player.U().Sd){var f=[];
b.navigationEndpoint&&g.V(b.navigationEndpoint,g.fT)&&g.V(b.navigationEndpoint,g.fT).browseId&&f.push(new Hob("openUrl","click",new Fob("/channel/"+g.V(b.navigationEndpoint,g.fT).browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&g.V(b.subscribeButton,
g.gT)){d.channel_id=g.V(b.subscribeButton,g.gT).channelId;var l;b=g.V(b.subscribeButton,g.gT);h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.tF(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.tF(b.subscriberCountText))):(b.subscriberCountText&&(e=g.tF(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.tF(b.subscriberCountWithSubscribeText)));var m,n=(null==(m=g.V(null==(l=b.signInEndpoint)?void 0:l.commandMetadata,g.y2))?void 0:m.url)||"";l={subscribeText:g.tF(b.unsubscribedButtonText),
subscribeCount:e||"",unsubscribeText:g.tF(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:n};d.standalone_subscribe_button_data=l}f=new Lob(c,"branding","branding",f,d);l=xpb(a);a.B.element.appendChild(l);f=new k4(l,m4(a),f);f.xG();g.N(f,f);a.K[c]=f}},Cpb=function(a,b){return function(){var c=g.Ia.apply(0,arguments);
a.Ma()||a.ra.push(g.Zu.Li(function(){b.apply(null,g.qa(c))}))}},Lpb=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.PT.prototype.zB=g.ea(28,function(a,b){var c=g.MV(this.yb());c&&c.zB(a,b)});
var H3={},I3=null;g.lb(K3,g.yv);g.k=K3.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.j)this.progress=0,this.coords=this.B;else if(this.isPlaying())return!1;J3(this);this.startTime=a=g.kb();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.gK();this.jn("play");this.isPaused()&&this.jn("resume");this.j=1;var b=g.fb(this);b in H3||(H3[b]=this);hob();iob(this,a);return!0};
g.k.stop=function(a){J3(this);this.j=0;a&&(this.progress=1);job(this,this.progress);this.onStop();this.Br()};
g.k.pause=function(){this.isPlaying()&&(J3(this),this.j=-1,this.jn("pause"))};
g.k.va=function(){0==this.j||this.stop(!1);this.jn("destroy");K3.Mf.va.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.hM=function(){this.jn("animate")};
g.k.jn=function(a){this.dispatchEvent(new kob(a,this))};
g.lb(kob,g.zb);g.lb(L3,K3);L3.prototype.C=function(){};
L3.prototype.hM=function(){this.C();L3.Mf.hM.call(this)};
L3.prototype.Br=function(){this.C();L3.Mf.Br.call(this)};
L3.prototype.gK=function(){this.C();L3.Mf.gK.call(this)};
g.lb(lob,L3);lob.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.y(oob,g.I);g.k=oob.prototype;g.k.listen=function(a,b,c,d){c=(0,g.gb)(c,d||this.B);a=g.WB(a,b,c);this.j.push(a);return a};
g.k.UE=function(a,b,c,d){c=(0,g.gb)(c,d||this.B);a=fob(a,b,c);this.j.push(a);return a};
g.k.Mc=function(a){g.XB(a);g.Hb(this.j,a)};
g.k.removeAll=function(){g.XB(this.j);this.j.length=0};
g.k.va=function(){this.removeAll();g.I.prototype.va.call(this)};g.y(rob,g.uV);g.k=rob.prototype;g.k.load=function(){g.uV.prototype.load.call(this);if(!O3(this)){var a=g.bWa(this.player.getVideoData());a?(a=qob(a,sob(this)),P3(this,a,!1)):tob(this)}};
g.k.unload=function(){P3(this,null);this.C&&(this.C.abort(),this.C=null);g.uV.prototype.unload.call(this)};
g.k.Ph=function(a,b){return O3(this)?"loadCustomEndscreenRenderer"===a?(a=qob(b,"new"),P3(this,a),!0):null:null};
g.k.getOptions=function(){return O3(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.dc=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<Mpb.length;f++){var h=Math.abs(b.width-Mpb[f]);if(-1===e||d>=h)e=f,d=h}d=Npb[e];this.B&&g.zs(this.B.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.G[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.Ks(e.element,m,f);g.Gs(e.element,n,p);g.wv(e.element,Opb);256<m||256<f?g.tv(e.element,"ytp-ce-large-round"):96<m||96<f?g.tv(e.element,"ytp-ce-medium-round"):g.tv(e.element,"ytp-ce-small-round");g.wv(e.element,Ppb);m=h.left+h.width/2;h=h.top+l/2;g.tv(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":
.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.wv(e.element,Npb);g.tv(e.element,d);(e=g.mf(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.zs(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())T3(this,this.endscreen.impressionUrls),(a=g.NE())&&this.endscreen.visualElement&&g.cF(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.G[a];g.tv(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.tv(b,"ytp-ce-shown");T3(this,c.impressionUrls);(b=g.NE())&&g.cF(b,c.visualElement);this.player.U().N&&this.player.ib("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.j[a];g.vv(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.vv(b,"ytp-ce-shown");this.player.U().N&&this.player.ib("endscreenelementhidden",a)}};
g.k.Kba=function(a){var b=this;a.target===window&&(new g.fv(function(){for(var c=g.u(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.wv(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var Mpb=[346,426,470,506,570,640,853,1280,1920],Npb="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),Ppb=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],Opb=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var Gob={yva:"current",HWa:"new"};var Iob={CLOSE:"close",y_a:"openUrl",SUBSCRIBE:"subscribe"},Job={Gta:"click",CLOSE:"close",BHa:"hidden",C5a:"rollOut",D5a:"rollOver",u7a:"shown"};Lob.prototype.Me=function(){var a=Mob(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var Jpb={Zna:"anchored",E2:"branding",CHANNEL:"channel",ova:"cta",EHa:"highlightText",ILa:"label",PLAYLIST:"playlist",POPUP:"popup",w$a:"speech",SUBSCRIBE:"subscribe",mdb:"title",VIDEO:"video",Pkb:"website"},Ipb={E2:"branding",kra:"card",yxa:"drawer",DHa:"highlight",YRa:"marker",N3a:"promotion",TEXT:"text",zmb:"widget"};g.y($3,g.I);g.k=$3.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.sJ(a,b,{id:c,namespace:"annotations_module"});d&&this.Wa.set(a,d);e&&this.bb.set(a,e);this.context.J.kf([a])};
g.k.xG=function(){this.context.B.subscribe("resize",this.RH,this)};
g.k.Ib=function(){return this.element};
g.k.iM=function(a,b,c,d,e,f){if(this.rb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.Ff(this.Ib())};
g.k.RH=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=V3(a);if(f){var h=Tob(f,a.target),l=function(){a.j&&e.context.J.pauseVideo();var m=e.context.videoData.Hf||!1,n=g.YA(f||"");m&&n&&(n.v||n.list)?e.context.J.Jo(n.v,b,n.list,!1):g.AG(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);l4(this.context.logger,c,l,d);Sob(f)||(c=g.NE(),d=b.itct,c&&d&&g.fF(c,g.LE(d)))}};
g.k.va=function(){this.Wa.clear();this.bb.clear();g.I.prototype.va.call(this)};
g.k.createElement=function(a){a=new g.W(a);g.N(this,a);return a.element};g.y(Vob,$3);g.k=Vob.prototype;g.k.vt=function(){this.ra&&e4(this,this.ra)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.J.getRootNode())?(a=g.Ls(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.RH=function(){var a=this.isAvailable();g.Ms(this.Ib(),a);g.xv(this.context.J.getRootNode(),g.JY.IV_DRAWER_ENABLED,a);F3(this.J)};
g.k.destroy=function(){this.J.zB(!1);try{this.J.getRootNode().removeChild(this.D)}catch(a){}g.VD(this.qa);g.bC(this.Ra);this.Va&&this.Va.dispose();this.G&&this.G.dispose();$3.prototype.destroy.call(this)};
g.k.findLastIndex=function(a){if(0===this.cards.length)return 0;var b=g.Eb(this.cards,function(c){return a.zf.startMs>c.zf.startMs||a.zf.startMs===c.zf.startMs&&a.zf.timestamp>=c.zf.timestamp?!0:!1});
return-1===b?0:b+1};
g.k.B6=function(){if(this.C){l4(this.context.logger,i4(this).aj.close);var a=g.NE();a&&this.N&&g.fF(a,this.N);d4(this)}};
g.k.Y6=function(){g.xv(this.D,"iv-drawer-scrolled",0<this.B.scrollTop)};
g.k.x9=function(){var a=g.NE(),b=i4(this);b=b?b.Ef:this.Ef;a&&b&&g.dF(a,[b])};
g.k.w9=function(){var a=g.NE(),b=i4(this);b=b?b.Ef:this.Ef;a&&b&&g.eF(a,[b])};
g.k.E3=function(){var a=i4(this);l4(this.context.logger,a.aj.X0);var b=g.NE();if(b&&a)if(this.J.L("web_infocards_teaser_show_logging_fix")){var c=[];a.Fj&&c.push(a.Fj);a.Ef&&c.push(a.Ef);0<c.length&&g.dF(b,c)}else g.dF(b,[a.Fj,a.Ef])};
g.k.y9=function(){var a=g.NE(),b=i4(this);a&&b&&g.eF(a,[b.Fj])};
g.k.D3=function(a){var b=i4(this),c=g.NE();this.j?a?(a=this.context.logger,l4(a,b.aj.zL),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Fj&&g.fF(c,b.Fj)):(a=this.context.logger,l4(a,b.aj.zL),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Ef&&g.fF(c,b.Ef)):(a=this.context.logger,l4(a,b.aj.zL),a.J.sendVideoStatsEngageEvent(4,void 0),c&&this.Ef&&g.fF(c,this.Ef))};g.y(j4,$3);j4.prototype.xG=function(){$3.prototype.xG.call(this);jpb(this)};
j4.prototype.show=function(){$3.prototype.show.call(this);var a=g.NE(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.dF(a,[g.LE(b.itct)])};
j4.prototype.hide=function(){$3.prototype.hide.call(this);var a=g.NE(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.eF(a,[g.LE(b.itct)])};g.y(k4,j4);k4.prototype.Cx=function(){g.tv(this.Ib(),"iv-branding");var a=this.annotation.data;this.B=this.createElement({I:"img",Ka:["branding-img","iv-click-target"],X:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.Ms(this.B,!1);var b=this.createElement({I:"button",Ka:["branding-img-container","ytp-button"]});b.appendChild(this.B);this.Ib().appendChild(b);var c=this.annotation.Me();c&&a4(this,b,c,this.annotation.id,a.session_data);npb(this,a)};
k4.prototype.show=function(){if(!this.isActive&&(j4.prototype.show.call(this),this.N||(this.Cx(),this.N=!0),g.Ms(this.Ib(),!0),this.isActive=!0,this.B)){try{kpb(this,this.B)}catch(a){}g.tv(this.context.J.getRootNode(),"ytp-branding-shown")}};
k4.prototype.hide=function(){this.isActive&&(j4.prototype.hide.call(this),g.Ms(this.Ib(),!1),this.isActive=!1,g.vv(this.context.J.getRootNode(),"ytp-branding-shown"))};
k4.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);j4.prototype.destroy.call(this)};g.y(ppb,j4);g.k=ppb.prototype;
g.k.Cx=function(){var a=this,b=this.annotation.data;if("cta"===this.annotation.style)var c=6;else if("video"===this.annotation.style||"playlist"===this.annotation.style)c=7;this.K=b.collapsedelay_ms||this.K;var d=["iv-promo","iv-promo-inactive"];this.Ib().setAttribute("aria-hidden","true");this.Ib().setAttribute("aria-label","Promotion");this.Ib().tabIndex=0;var e=this.annotation.Me(),f=b.image_url;if(f){var h=this.createElement({I:"div",Ka:["iv-promo-img","iv-click-target"]});f=this.createElement({I:"img",
X:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?(f=this.createElement({I:"span",S:"iv-promo-video-duration",xa:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=this.createElement({I:"span",S:"iv-promo-playlist-length",xa:b.playlist_length.toString()}),h.appendChild(f));e&&a4(this,h,e,this.annotation.id,b.session_data,void 0,c)}e?(f=this.createElement({I:"a",S:"iv-promo-txt"}),g.Ke(f,V3(e)),this.j=f):this.j=this.createElement({I:"div",S:"iv-promo-txt"});switch(this.annotation.style){case "cta":case "website":var l=
this.createElement({I:"p",V:[{I:"strong",xa:b.text_line_1}]});var m=this.createElement({I:"p",V:[{I:"span",S:"iv-promo-link",xa:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=this.createElement({I:"button",Ka:["iv-promo-round-expand-icon","ytp-button"]});f=this.createElement({I:"button",Ka:["iv-button","iv-promo-button"],V:[{I:"span",S:"iv-button-content",xa:f}]});var p=this.createElement({I:"div",S:"iv-promo-button-container"});p.appendChild(f);e&&a4(this,
this.Ib(),e,this.annotation.id,b.session_data,void 0,c)}g.tv(this.j,"iv-click-target");e&&a4(this,this.j,e,this.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=this.createElement({I:"p",V:[{I:"span",xa:b.text_line_1}]}),m=this.createElement({I:"p",V:[{I:"strong",xa:b.text_line_2}]}),b.is_live&&(l=m,m=this.createElement({I:"span",Ka:["yt-badge","iv-promo-badge-live"],xa:"LIVE NOW"})),g.tv(this.j,"iv-click-target"),e&&a4(this,this.j,e,this.annotation.id,b.session_data,void 0,
c),d.push("iv-promo-video")}l&&this.j.appendChild(l);m&&this.j.appendChild(m);this.N.appendChild(this.j);p&&this.N.appendChild(p);c=this.createElement({I:"div",S:"iv-promo-actions"});this.B=this.createElement({I:"button",Ka:["iv-promo-expand","ytp-button"]});this.B.title="Expand";this.context.j.listen(this.B,"click",function(q){spb(a,5E3,q)});
c.appendChild(this.B);g.Ms(this.B,!1);this.context.j.listen(this.Ib(),"mouseover",this.t8,this);this.context.j.listen(this.Ib(),"mouseout",this.s8,this);this.context.j.listen(this.Ib(),"touchend",function(q){spb(a,5E3,q)});
this.C=this.createElement({I:"button",Ka:["iv-promo-close","ytp-button"]});this.C.title="Close";this.context.j.listen(this.C,"click","cta"===this.annotation.style&&b.text_line_3?this.o8:this.n8,this);c.appendChild(this.C);g.uv(this.Ib(),d);h&&(g.Af(this.Ib(),h),n&&h.appendChild(n));g.Af(this.Ib(),this.N);g.Af(this.Ib(),c)};
g.k.show=function(){this.isActive||(j4.prototype.show.call(this),this.Y||(this.Cx(),this.Y=!0),g.Ms(this.Ib(),!0),g.Bg(function(){g.vv(this.Ib(),"iv-promo-inactive")},100,this),this.Ib().removeAttribute("aria-hidden"),this.isActive=!0,upb(this),qpb(this),rpb(this,this.K))};
g.k.hide=function(){this.isActive&&(g.tv(this.Ib(),"iv-promo-inactive"),this.isActive=!1,this.Ib().setAttribute("aria-hidden","true"))};
g.k.iM=function(a,b,c,d,e,f){return this.isCollapsed?!1:j4.prototype.iM.call(this,a,b,c,d,e,f)};
g.k.t8=function(a){this.Z=!0;spb(this,500,a)};
g.k.s8=function(){this.Z=!1;tpb(this)};
g.k.n8=function(a){a.stopPropagation();this.hide()};
g.k.o8=function(a){a.stopPropagation();upb(this);this.isCollapsed=!0;g.tv(this.Ib(),"iv-promo-collapsed-no-delay");this.G.start()};
g.k.destroy=function(){this.G.dispose();j4.prototype.destroy.call(this)};g.y(wpb,g.uV);g.k=wpb.prototype;g.k.Ph=function(a,b){if(!Lpb(this.player.U().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.d2(b))&&Bpb(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(Zob(this.j,b),F3(this.player)),!0}return null};
g.k.getOptions=function(){return Lpb(this.player.U().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.vu=function(){var a=this.player.U(),b=this.player.getVideoData(),c=a.annotationsLoadPolicy||b.annotationsLoadPolicy;return g.xT(b)||g.IT(this.player.app)?!1:1===c&&!b.rW||a.Na.get(b.videoId)||g.nT(b)||g.cWa(b)?!0:!1};
g.k.pK=function(){if(this.C){var a=this.player.ob().getVideoContentRect(!0);g.Ks(this.C.element,a.width,a.height);g.Gs(this.C.element,a.left,a.top)}if(this.j){var b=this.player.Bn();a=this.j;b=b.width;g.xv(a.D,"iv-drawer-small",426>=b);g.xv(a.D,"iv-drawer-big",1280<=b)}};
g.k.F3=function(a){ypb(this,a.state);g.$F(a.state,2)&&(this.Hk()&&this.Xo()&&2!==this.player.getPresentingPlayerType()&&this.AB(!1),this.zB(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.G=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.fB(h)&&h.responseXML?h.responseXML:null)&&(Bpb(b,h),g.tv(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.uV.prototype.load.call(this);ypb(this,this.player.getPlayerStateObject());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.uC()&&(a=Cpb(this,a));var e={format:"XML",onFinish:a,onError:function(){b.G=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.U().Na.get(d);f&&Dpb(e,f);f=f&&(f.CN||f.WH);if(!c.Qu||f)c.Va?zpb(this,c.Va,e):(this.N=function(){if(!b.Z)b.onVideoDataChange(e);var h=b.player.getVideoData();(null==h?0:g.mT(h))&&!b.qa&&Hpb(b,h)},this.player.addEventListener("videodatachange",this.N));
g.WT(this.player,this.C.element,4);this.pK();(f=g.nT(c))&&Gpb(this,f);(f=g.cWa(c))&&f.featuredChannel&&Kpb(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null);this.Rg=g.tf("ytp-cards-button",this.player.getRootNode());g.mT(c)&&Hpb(this,c)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Va&&zpb(this,b.Va,a)};
g.k.unload=function(){this.player.rf("annotations_module");for(var a=g.u(Object.keys(this.K)),b=a.next();!b.done;b=a.next())this.K[b.value].destroy();this.Y=null;this.j&&(this.j.destroy(),this.j=null,F3(this.player));this.Z=!1;this.G&&(this.G.abort(),this.G=null);this.qa=!1;this.K={};this.B.hide();g.uV.prototype.unload.call(this);this.C.detach();this.N&&(this.player.removeEventListener("videodatachange",this.N),this.N=null)};
g.k.m_=function(a){a===this.player.getVideoData().videoId&&(this.loaded?Epb(this):this.load())};
g.k.Hk=function(){var a;return(null==(a=this.j)?void 0:a.isAvailable())||this.qa};
g.k.Xo=function(){return!!this.j&&this.j.C};
g.k.AB=function(a,b,c){b=void 0===b?!1:b;this.Hk();this.j&&(a?c?c4(this.j,c,b):c4(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):d4(this.j))};
g.k.zB=function(a,b){this.player.publish(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.va=function(){this.player.U().Na.unsubscribe("vast_info_card_add",this.m_,this);g.vv(this.player.getRootNode(),g.JY.IV_DRAWER_OPEN);for(var a=this.ra,b=g.Zu,c=0,d=a.length;c<d;c++)b.Kj(a[c]);this.ra.length=0;g.uV.prototype.va.call(this)};
g.k.createElement=function(a){a=new g.W(a);g.N(this,a);return a.element};g.tV("annotations_module",wpb);g.tV("creatorendscreen",rob);})(_yt_player);
